# This will run the project in a node environment on gitlab's servers
image: node:latest

# These are the stages that the ci process will cycle through
# starting with build, then test and lastly deploy
stages:
  - build
  - test

# This will compile the application's frontend and produce a build folder
build:
  stage: build
  only:
    - develop
  script:
    - yarn install && yarn build
  artifacts:
    paths:
      - build/
    expire_in: 30 days

# This will run tests on the application using a test framework. For example, Jest
test:
  stage: test
  dependencies:
    - build
  script:
    - cd backend/
    - yarn install
    - yarn jest --forceExit --detectOpenHandles
