// User Actions
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const LOG_OUT = 'LOG_OUT';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const SET_NEW_USER_NULL = 'SET_NEW_USER_NULL';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

// Product Actions
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_ONE_PRODUCT = 'FETCH_ONE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const NEW_PRODUCT = 'NEW_PRODUCT';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';

// Order Actions
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ACCOUNT_BALANCE = 'FETCH_ACCOUNT_BALANCE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const PLACE_ORDER = 'PLACE_ORDER';
export const PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE';
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
export const CALCULATE_COST = 'CALCULATE_COST';
